# Generated by Django 5.1 on 2024-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("slug", models.SlugField(max_length=250)),
                ("content", models.TextField(verbose_name="содержимое")),
                ("image", models.ImageField(upload_to="posts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                ("views", models.IntegerField()),
            ],
            options={
                "verbose_name": "публикация",
                "verbose_name_plural": "публикации",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="blog_post_created_45f0c6_idx"
                    )
                ],
            },
        ),
    ]
