# Generated by Django 5.1 on 2024-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_slug_alter_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=250, unique_for_date="created_at", verbose_name="slug"
            ),
        ),
    ]
