# Generated by Django 5.1 on 2024-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "Rubles"), ("USD", "Dollars")],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
