# Generated by Django 5.1 on 2024-09-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_currency_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "Rubles"), ("USD", "Dollars")],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="статус"),
        ),
        migrations.AlterField(
            model_name="version",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="catalog.product",
                verbose_name="продукт",
            ),
        ),
    ]
