# Generated by Django 5.1 on 2024-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_contact_alter_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "Rubles"), ("USD", "Dollars")],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, default="product", max_length=100, null=True
            ),
        ),
    ]
