# Generated by Django 5.1 on 2024-09-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_currency_alter_version_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="version",
            old_name="product_id",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "Rubles"), ("USD", "Dollars")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
