# Generated by Django 4.2 on 2024-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_owner_alter_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Активен", "Active"), ("Не активен", "Not Active")],
                default="Не активен",
                max_length=10,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "Rubles"), ("USD", "Dollars")],
                default="USD",
                max_length=3,
                verbose_name="валюта",
            ),
        ),
    ]
